### ISSUE TITLE
Use WP Cron to check for extension updates

### ISSUE THREAD

**Issue by ghost** [ThemeFuse/Unyson-Update-Extension#3]
Prevent site blocking when the versions transient/cache has exipred and for each extension a request is made.

**Comment by ghost** [comment]
WP Cron is not working on all servers, so this will cause clients with outdated extensions. Abort

**Comment by andreiglingeanu** [comment]
Actually, WP Cron is available everywhere. It is just implemented in different ways everywhere, it knows how to degrade itself into executing tasks onto a regular request.

It might be a good idea to implement that thing.
